#!/bin/env python

import platform

#print (platform.architecture())
#print (platform.machine())
print (platform.platform())
#print (platform.release())
#print (platform.system())
#print (platform.uname())
#print (platform.version())
